name: flutter_application_1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  supabase_flutter: ^2.8.0
  go_router: ^17.0.0
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.0
  provider: ^6.1.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/hoteles/
    - assets/images/motel/
    - assets/images/restaurantes/
    - assets/images/ciudades/
    - assets/images/hoteles/nh_cali_royale/
    - assets/images/hoteles/aquamare/
    - assets/images/hoteles/country_international/
    - assets/images/hoteles/estelar_altamira/
    - assets/images/hoteles/irotama_lago/
    - assets/images/hoteles/las_americas_torre_del_mar/
    - assets/images/hoteles/san_fernando_plaza/
    - assets/images/hoteles/sonesta_bogota/
    - assets/images/hoteles/suma_wasi/
    - assets/images/hoteles/sonesta_ibague/
